### ISSUE TITLE
WebRTC App not Launching OpenVidu Client

### ISSUE THREAD

**Issue by AdrianDAlessandro** [ove/ove-apps#265]
**Problem:**

I am currently trying to use the WebRTC App provided with OVE. I have gotten to the point of Launching the app in the OVE Application Launcher, which appears to be successful. I then can access the WebRTC App controller in browser and initialise the call (I believe), but then I cannot access the OPENVIDU_HOST url as described in the last line of [the docs](https://ove.readthedocs.io/en/stable/ove-apps/packages/ove-app-webrtc/README.html#controlling-the-app).

**Detail:**

My steps so far have been:
1. Launch the OVE server using the docker installation provided.
2. Open the Application Launcher and launch a WebRTC application to one of the spaces.
3. Open the controller the the WebRTC section and click the only button available (the one with the people icons). I assume this is what is meant by initialising the conference call in [the docs](https://ove.readthedocs.io/en/stable/ove-apps/packages/ove-app-webrtc/README.html#controlling-the-app).
4. Navigate to the OPENVIDU_HOST address defined in the docker-compose.yml – **this is where it fails** the url simply doesn't exist.
 
Digging into the logs, there is an indication of an error, but I’m not sure where to start with interpreting it:

```
ovehub-ove-apps_1                          | Writable {
ovehub-ove-apps_1                          |   _writableState:
ovehub-ove-apps_1                          |    WritableState {
ovehub-ove-apps_1                          |      objectMode: false,
ovehub-ove-apps_1                          |      highWaterMark: 16384,
ovehub-ove-apps_1                          |      finalCalled: false,
ovehub-ove-apps_1                          |      needDrain: false,
ovehub-ove-apps_1                          |      ending: false,
ovehub-ove-apps_1                          |      ended: false,
ovehub-ove-apps_1                          |      finished: false,
ovehub-ove-apps_1                          |      destroyed: false,
ovehub-ove-apps_1                          |      decodeStrings: true,
ovehub-ove-apps_1                          |      defaultEncoding: 'utf8',
ovehub-ove-apps_1                          |      length: 0,
ovehub-ove-apps_1                          |      writing: false,
ovehub-ove-apps_1                          |      corked: 0,
ovehub-ove-apps_1                          |      sync: true,
ovehub-ove-apps_1                          |      bufferProcessing: false,
ovehub-ove-apps_1                          |      onwrite: [Function: bound onwrite],
ovehub-ove-apps_1                          |      writecb: null,
ovehub-ove-apps_1                          |      writelen: 0,
ovehub-ove-apps_1                          |      bufferedRequest: null,
ovehub-ove-apps_1                          |      lastBufferedRequest: null,
ovehub-ove-apps_1                          |      pendingcb: 0,
ovehub-ove-apps_1                          |      prefinished: false,
ovehub-ove-apps_1                          |      errorEmitted: false,
ovehub-ove-apps_1                          |      emitClose: true,
ovehub-ove-apps_1                          |      autoDestroy: false,
ovehub-ove-apps_1                          |      bufferedRequestCount: 0,
ovehub-ove-apps_1                          |      corkedRequestsFree:
ovehub-ove-apps_1                          |       { next: null,
ovehub-ove-apps_1                          |         entry: null,
ovehub-ove-apps_1                          |         finish: [Function: bound onCorkedFinish] } },
ovehub-ove-apps_1                          |   writable: true,
ovehub-ove-apps_1                          |   _events:
ovehub-ove-apps_1                          |    [Object: null prototype] {
ovehub-ove-apps_1                          |      response: [Function: handleResponse],
ovehub-ove-apps_1                          |      error: [Function: handleRequestError] },
ovehub-ove-apps_1                          |   _eventsCount: 2,
ovehub-ove-apps_1                          |   _maxListeners: undefined,
ovehub-ove-apps_1                          |   _options:
ovehub-ove-apps_1                          |    { maxRedirects: 21,
ovehub-ove-apps_1                          |      maxBodyLength: 10485760,
ovehub-ove-apps_1                          |      protocol: 'https:',
ovehub-ove-apps_1                          |      path: '/api/sessions',
ovehub-ove-apps_1                          |      method: 'post',
ovehub-ove-apps_1                          |      headers:
ovehub-ove-apps_1                          |       { Accept: 'application/json, text/plain, */*',
ovehub-ove-apps_1                          |         'Content-Type': 'application/json',
ovehub-ove-apps_1                          |         Authorization: 'Basic T1BFTlZJRFVBUFA6TVlfU0VDUkVU',
ovehub-ove-apps_1                          |         'User-Agent': 'axios/0.18.0',
ovehub-ove-apps_1                          |         'Content-Length': 170 },
ovehub-ove-apps_1                          |      agent: undefined,
ovehub-ove-apps_1                          |      auth: undefined,
ovehub-ove-apps_1                          |      hostname: '146.179.34.13',
ovehub-ove-apps_1                          |      port: '4443',
ovehub-ove-apps_1                          |      nativeProtocols: { 'http:': [Object], 'https:': [Object] },
ovehub-ove-apps_1                          |      pathname: '/api/sessions' },
ovehub-ove-apps_1                          |   _ended: false,
ovehub-ove-apps_1                          |   _ending: true,
ovehub-ove-apps_1                          |   _redirectCount: 0,
ovehub-ove-apps_1                          |   _redirects: [],
ovehub-ove-apps_1                          |   _requestBodyLength: 170,
ovehub-ove-apps_1                          |   _requestBodyBuffers:
ovehub-ove-apps_1                          |    [ { data:
ovehub-ove-apps_1                          |         <Buffer 7b 22 6d 65 64 69 61 4d 6f 64 65 22 3a 22 52 4f 55 54 45 44 22 2c 22 72 65 63 6f 72 64 69 6e 67 4d 6f 64 65 22 3a 22 4d 41 4e 55 41 4c 22 2c 22 64 65 ... >,
ovehub-ove-apps_1                          |        encoding: undefined } ],
ovehub-ove-apps_1                          |   _onNativeResponse: [Function],
ovehub-ove-apps_1                          |   _currentRequest:
ovehub-ove-apps_1                          |    ClientRequest {
ovehub-ove-apps_1                          |      _events:
ovehub-ove-apps_1                          |       [Object: null prototype] {
ovehub-ove-apps_1                          |         response: [Function],
ovehub-ove-apps_1                          |         socket: [Function],
ovehub-ove-apps_1                          |         abort: [Function],
ovehub-ove-apps_1                          |         aborted: [Function],
ovehub-ove-apps_1                          |         connect: [Function],
ovehub-ove-apps_1                          |         error: [Function],
ovehub-ove-apps_1                          |         timeout: [Function] },
ovehub-ove-apps_1                          |      _eventsCount: 7,
ovehub-ove-apps_1                          |      _maxListeners: undefined,
ovehub-ove-apps_1                          |      output: [],
ovehub-ove-apps_1                          |      outputEncodings: [],
ovehub-ove-apps_1                          |      outputCallbacks: [],
ovehub-ove-apps_1                          |      outputSize: 0,
ovehub-ove-apps_1                          |      writable: true,
ovehub-ove-apps_1                          |      _last: true,
ovehub-ove-apps_1                          |      chunkedEncoding: false,
ovehub-ove-apps_1                          |      shouldKeepAlive: false,
ovehub-ove-apps_1                          |      useChunkedEncodingByDefault: true,
ovehub-ove-apps_1                          |      sendDate: false,
ovehub-ove-apps_1                          |      _removedConnection: false,
ovehub-ove-apps_1                          |      _removedContLen: false,
ovehub-ove-apps_1                          |      _removedTE: false,
ovehub-ove-apps_1                          |      _contentLength: null,
ovehub-ove-apps_1                          |      _hasBody: true,
ovehub-ove-apps_1                          |      _trailer: '',
ovehub-ove-apps_1                          |      finished: false,
ovehub-ove-apps_1                          |      _headerSent: true,
ovehub-ove-apps_1                          |      socket:
ovehub-ove-apps_1                          |       TLSSocket {
ovehub-ove-apps_1                          |         _tlsOptions: [Object],
ovehub-ove-apps_1                          |         _secureEstablished: false,
ovehub-ove-apps_1                          |         _securePending: false,
ovehub-ove-apps_1                          |         _newSessionPending: false,
ovehub-ove-apps_1                          |         _controlReleased: true,
ovehub-ove-apps_1                          |         _SNICallback: null,
ovehub-ove-apps_1                          |         servername: null,
ovehub-ove-apps_1                          |         alpnProtocol: null,
ovehub-ove-apps_1                          |         authorized: false,
ovehub-ove-apps_1                          |         authorizationError: null,
ovehub-ove-apps_1                          |         encrypted: true,
ovehub-ove-apps_1                          |         _events: [Object],
ovehub-ove-apps_1                          |         _eventsCount: 8,
ovehub-ove-apps_1                          |         connecting: false,
ovehub-ove-apps_1                          |         _hadError: true,
ovehub-ove-apps_1                          |         _handle: null,
ovehub-ove-apps_1                          |         _parent: null,
ovehub-ove-apps_1                          |         _host: null,
ovehub-ove-apps_1                          |         _readableState: [ReadableState],
ovehub-ove-apps_1                          |         readable: false,
ovehub-ove-apps_1                          |         _maxListeners: undefined,
ovehub-ove-apps_1                          |         _writableState: [WritableState],
ovehub-ove-apps_1                          |         writable: false,
ovehub-ove-apps_1                          |         allowHalfOpen: false,
ovehub-ove-apps_1                          |         _sockname: null,
ovehub-ove-apps_1                          |         _pendingData: null,
ovehub-ove-apps_1                          |         _pendingEncoding: '',
ovehub-ove-apps_1                          |         server: undefined,
ovehub-ove-apps_1                          |         _server: null,
ovehub-ove-apps_1                          |         ssl: null,
ovehub-ove-apps_1                          |         _requestCert: true,
ovehub-ove-apps_1                          |         _rejectUnauthorized: false,
ovehub-ove-apps_1                          |         parser: null,
ovehub-ove-apps_1                          |         _httpMessage: [Circular],
ovehub-ove-apps_1                          |         write: [Function: writeAfterFIN],
ovehub-ove-apps_1                          |         [Symbol(res)]: [TLSWrap],
ovehub-ove-apps_1                          |         [Symbol(asyncId)]: 816,
ovehub-ove-apps_1                          |         [Symbol(lastWriteQueueSize)]: 419,
ovehub-ove-apps_1                          |         [Symbol(timeout)]: null,
ovehub-ove-apps_1                          |         [Symbol(kBytesRead)]: 0,
ovehub-ove-apps_1                          |         [Symbol(kBytesWritten)]: 419,
ovehub-ove-apps_1                          |         [Symbol(connect-options)]: [Object] },
ovehub-ove-apps_1                          |      connection:
ovehub-ove-apps_1                          |       TLSSocket {
ovehub-ove-apps_1                          |         _tlsOptions: [Object],
ovehub-ove-apps_1                          |         _secureEstablished: false,
ovehub-ove-apps_1                          |         _securePending: false,
ovehub-ove-apps_1                          |         _newSessionPending: false,
ovehub-ove-apps_1                          |         _controlReleased: true,
ovehub-ove-apps_1                          |         _SNICallback: null,
ovehub-ove-apps_1                          |         servername: null,
ovehub-ove-apps_1                          |         alpnProtocol: null,
ovehub-ove-apps_1                          |         authorized: false,
ovehub-ove-apps_1                          |         authorizationError: null,
ovehub-ove-apps_1                          |         encrypted: true,
ovehub-ove-apps_1                          |         _events: [Object],
ovehub-ove-apps_1                          |         _eventsCount: 8,
ovehub-ove-apps_1                          |         connecting: false,
ovehub-ove-apps_1                          |         _hadError: true,
ovehub-ove-apps_1                          |         _handle: null,
ovehub-ove-apps_1                          |         _parent: null,
ovehub-ove-apps_1                          |         _host: null,
ovehub-ove-apps_1                          |         _readableState: [ReadableState],
ovehub-ove-apps_1                          |         readable: false,
ovehub-ove-apps_1                          |         _maxListeners: undefined,
ovehub-ove-apps_1                          |         _writableState: [WritableState],
ovehub-ove-apps_1                          |         writable: false,
ovehub-ove-apps_1                          |         allowHalfOpen: false,
ovehub-ove-apps_1                          |         _sockname: null,
ovehub-ove-apps_1                          |         _pendingData: null,
ovehub-ove-apps_1                          |         _pendingEncoding: '',
ovehub-ove-apps_1                          |         server: undefined,
ovehub-ove-apps_1                          |         _server: null,
ovehub-ove-apps_1                          |         ssl: null,
ovehub-ove-apps_1                          |         _requestCert: true,
ovehub-ove-apps_1                          |         _rejectUnauthorized: false,
ovehub-ove-apps_1                          |         parser: null,
ovehub-ove-apps_1                          |         _httpMessage: [Circular],
ovehub-ove-apps_1                          |         write: [Function: writeAfterFIN],
ovehub-ove-apps_1                          |         [Symbol(res)]: [TLSWrap],
ovehub-ove-apps_1                          |         [Symbol(asyncId)]: 816,
ovehub-ove-apps_1                          |         [Symbol(lastWriteQueueSize)]: 419,
ovehub-ove-apps_1                          |         [Symbol(timeout)]: null,
ovehub-ove-apps_1                          |         [Symbol(kBytesRead)]: 0,
ovehub-ove-apps_1                          |         [Symbol(kBytesWritten)]: 419,
ovehub-ove-apps_1                          |         [Symbol(connect-options)]: [Object] },
ovehub-ove-apps_1                          |      _header:
ovehub-ove-apps_1                          |       'POST /api/sessions HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/json\r\nAuthorization: Basic T1BFTlZJRFVBUFA6TVlfU0VDUkVU\r\nUser-Agent: axios/0.18.0\r\nContent-Length: 170\r\nHost: 146.179.34.13:4443\r\nConnection: close\r\n\r\n',
ovehub-ove-apps_1                          |      _onPendingData: [Function: noopPendingOutput],
ovehub-ove-apps_1                          |      agent:
ovehub-ove-apps_1                          |       Agent {
ovehub-ove-apps_1                          |         _events: [Object],
ovehub-ove-apps_1                          |         _eventsCount: 1,
ovehub-ove-apps_1                          |         _maxListeners: undefined,
ovehub-ove-apps_1                          |         defaultPort: 443,
ovehub-ove-apps_1                          |         protocol: 'https:',
ovehub-ove-apps_1                          |         options: [Object],
ovehub-ove-apps_1                          |         requests: {},
ovehub-ove-apps_1                          |         sockets: [Object],
ovehub-ove-apps_1                          |         freeSockets: {},
ovehub-ove-apps_1                          |         keepAliveMsecs: 1000,
ovehub-ove-apps_1                          |         keepAlive: false,
ovehub-ove-apps_1                          |         maxSockets: Infinity,
ovehub-ove-apps_1                          |         maxFreeSockets: 256,
ovehub-ove-apps_1                          |         maxCachedSessions: 100,
ovehub-ove-apps_1                          |         _sessionCache: [Object] },
ovehub-ove-apps_1                          |      socketPath: undefined,
ovehub-ove-apps_1                          |      timeout: undefined,
ovehub-ove-apps_1                          |      method: 'POST',
ovehub-ove-apps_1                          |      insecureHTTPParser: undefined,
ovehub-ove-apps_1                          |      path: '/api/sessions',
ovehub-ove-apps_1                          |      _ended: false,
ovehub-ove-apps_1                          |      res: null,
ovehub-ove-apps_1                          |      aborted: undefined,
ovehub-ove-apps_1                          |      timeoutCb: null,
ovehub-ove-apps_1                          |      upgradeOrConnect: false,
ovehub-ove-apps_1                          |      parser: null,
ovehub-ove-apps_1                          |      maxHeadersCount: null,
ovehub-ove-apps_1                          |      _redirectable: [Circular],
ovehub-ove-apps_1                          |      [Symbol(isCorked)]: false,
ovehub-ove-apps_1                          |      [Symbol(outHeadersKey)]:
ovehub-ove-apps_1                          |       [Object: null prototype] {
ovehub-ove-apps_1                          |         accept: [Array],
ovehub-ove-apps_1                          |         'content-type': [Array],
ovehub-ove-apps_1                          |         authorization: [Array],
ovehub-ove-apps_1                          |         'user-agent': [Array],
ovehub-ove-apps_1                          |         'content-length': [Array],
ovehub-ove-apps_1                          |         host: [Array] } },
ovehub-ove-apps_1                          |   _currentUrl: 'https://OPENVIDU_HOST/api/sessions' }
ovehub-ove-apps_1                          | [ERROR] 25/01/2023, 2:25:23.179 pm - webrtc           : Error: [object Object]
ovehub-ove-apps_1                          |     at /usr/src/app/node_modules/openvidu-node-client/lib/Session.js:420:28
ovehub-ove-apps_1                          |     at process._tickCallback (internal/process/next_tick.js:68:7)
```
*Note:* `OPENVIDU_HOST` has been replaced

**Comment by bcd00** [comment]
Confirm c59feb1 and merge

**Comment by AdrianDAlessandro** [comment]
> Confirm [c59feb1](https://github.com/ove/ove-apps/commit/c59feb16d9b5f1e910d9dd1c527274e2e448c6c8) and merge

Does this mean a working version with the WebRTC app will be available soon?

**Comment by bcd00** [comment]
> Does this mean a working version with the WebRTC app will be available soon?

Once it's merged and tested in situ I can confirm whether this update resolves the issue entirely, but I am hoping to have this fixed soon.

**Comment by AdrianDAlessandro** [comment]
Excellent! That will line up well with our timing, should it fix the issue. Thanks for all the work!

**Comment by AdrianDAlessandro** [comment]
WebRTC works in the new version of OVE - as long as you have your own deployment of OpenVidu - https://docs.openvidu.io/en/stable/deployment/ce/on-premises/
