### ISSUE TITLE
OVE video app does not allow playing of videos

### ISSUE THREAD

**Issue by DavidAkroyd** [ove/ove-apps#36]
Videos that are loaded as part of a state do not play when the Play All button is pressed

Attempting to use the `/operation/play` results in the following message:

```
Error: WebSocket is not open: readyState 3 (CLOSED)
    at WebSocket.send (/usr/src/app/node_modules/ws/lib/websocket.js:314:19)
    at /usr/src/app/packages/ove-app-videos/dist/index.js:88:16
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/app/node_modules/express/lib/router/index.js:281:22
    at param (/usr/src/app/node_modules/express/lib/router/index.js:354:14)
    at param (/usr/src/app/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:410:3)
```

This is solved/play works upon restarting ove-apps

**Comment by DavidAkroyd** [comment]
This has been solved in #41
